/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `tb_classes`;

DROP TABLE IF EXISTS `tb_student`;

CREATE TABLE `tb_student` (
  `sn` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `classes_id` BIGINT UNSIGNED NOT NULL,
  `name` TEXT NOT NULL,
  `age` INT NULL,
  `score` DOUBLE NULL,
  `birth` DATETIME NULL)
 ENGINE=InnoDB;

CREATE INDEX `classes_id_i`
  ON `tb_student` (`classes_id`);

CREATE TABLE `tb_classes` (
  `sn` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL)
 ENGINE=InnoDB;

CREATE UNIQUE INDEX `name_i`
  ON `tb_classes` (`name`);

